openapi: 3.0.3
info:
  title: virgin Airlines Passenger Notification WebSocket API
  version: 1.0.0
  description: >
    WebSocket endpoint used by passenger clients to receive real-time notifications
    (e.g. flight gate changes). The client connects directly to the notification
    WebSocket and optionally sends a lightweight hello payload to identify the trip context.
servers:
  - url: ws://4.198.139.1:5533
    description: Direct notification WebSocket host

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: OIDC bearer token

  schemas:
    NotificationEnvelope:
      type: object
      required: [type, eventType, correlationId, occurredAt, payload]
      properties:
        type:
          type: string
          enum: [notification]
        eventType:
          type: string
          enum: [flight.changed]
        correlationId:
          type: string
        occurredAt:
          type: string
          format: date-time
        payload:
          $ref: '#/components/schemas/FlightChangedNotificationPayload'

    FlightChangedNotificationPayload:
      type: object
      required: [passengerId, bookingPnr, flightId, flightNumber, change, message]
      properties:
        passengerId:
          type: string
          format: uuid
        bookingPnr:
          type: string
          minLength: 6
          maxLength: 6
        flightId:
          type: string
          format: uuid
        flightNumber:
          type: string
          example: VA801
        change:
          type: object
          required: [field, oldValue, newValue]
          properties:
            field:
              type: string
              example: boardingGate
            oldValue:
              type: string
              nullable: true
              example: "12"
            newValue:
              type: string
              example: "14"
        message:
          type: string
          description: AI-tailored notification message (e.g. produced via OpenAI call)
          example: "Hi Joe, your gate for VA801 has changed from 12 to 14. Head to Gate 14 when you're ready."

paths:
  /mobileapp:
    get:
      summary: Passenger notification WebSocket (direct)
      operationId: connectPassengerNotifications
      description: >
        WebSocket upgrade endpoint for mobile app notifications. Clients connect to
        `ws://4.198.139.1:5533/mobileapp` and can optionally send a hello payload
        containing `passengerId` and `bookingPnr`.
      responses:
        '101':
          description: Switching Protocols (WebSocket established)
